### ISSUE TITLE
Having to save two times

### ISSUE THREAD

**Issue by chrisfls** [hamdanjaveed/Not-So-Annoying-Whitespace-Fixer#1]
I'm having to save each file two times, because it's removing the whitespaces after brackets saves the file.

**Comment by hamdanjaveed** [comment]
Hmm, I'll look into it when I have some time

**Comment by hamdanjaveed** [comment]
Bug fixed in version 1.0.1

**Comment by cheesypoof** [comment]
I think this change has caused a regression. As soon as I open a file now, whitespace is trimmed and the file is added to the working set. This is undesirable because sometimes you just want to open a file to read it, and not perform edits.

**Comment by hamdanjaveed** [comment]
My bad :( That issue should be fixed now

**Comment by cheesypoof** [comment]
Confirmed - works great now. Thanks @hamdanjaveed!

**Comment by hamdanjaveed** [comment]
Sweet :D

**Comment by chrisfls** [comment]
Thanks :smile: 
Everything is fine now :+1: 

(I forgot to add that I'm using Brackets 0.44)
